version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: "redis:7.0.5-alpine"
    restart: unless-stopped

