basePath: /v1
definitions:
  handlers.LanguageView:
    properties:
      id:
        type: integer
      name:
        type: string
      version:
        type: string
    type: object
  httputil.HttpError:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  stella.SubmissionInput:
    properties:
      additional_files:
        type: string
      expected_output:
        type: string
      language_id:
        type: integer
      source_code:
        type: string
      std_in:
        type: string
      token:
        type: string
    type: object
  stella.SubmissionOutput:
    properties:
      executed:
        type: boolean
      exit_code:
        type: integer
      memory:
        type: number
      output_matched:
        type: boolean
      stderr:
        type: string
      stdout:
        type: string
      time:
        example: "0"
        type: string
      token:
        type: string
    type: object
host: localhost:4000
info:
  contact: {}
  description: Code execution API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/khai93/stella/blob/main/LICENSE
  title: Stella API
  version: "1.0"
paths:
  /languages:
    get:
      description: Gets the languages from the Execution Service and sends it as response
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LanguageView'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
  /submissions/{token}:
    get:
      description: Get a submission from the SubsmissionService and return the response
      parameters:
      - description: Submission Token
        in: path
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stella.SubmissionOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
  /submissions/create:
    post:
      description: Creates a Submission to SubmissionService and returns the response
      parameters:
      - description: Submission Input
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/stella.SubmissionInput'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/stella.SubmissionOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HttpError'
swagger: "2.0"
